style:
  tag:
    color: blue
    width_percentage: 30
    min_width: 15
  comment:
    color: white
    width_percentage: 70
    min_width: 30
  snippet:
    color: white
    width_percentage: 0

cheats:
  paths:
    - ~/.local/share/navi/cheats
